import "./globals.css";
import { Inter } from "next/font/google";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const licenseKey = process.env.NEXT_PUBLIC_NEW_RELIC_LICENSE_KEY;
const applicationID = process.env.NEXT_PUBLIC_NEW_RELIC_APPLICATION_ID;

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <head>
                <Script
                    dangerouslySetInnerHTML={{
                        __html: `
                        window.NREUM || (NREUM = {});

                        NREUM.init = {
                            distributed_tracing: { enabled: true },
                            privacy: { cookies_enabled: true },
                            ajax: { deny_list: ["bam.nr-data.net"] },
                        };

                        NREUM.loader_config = {
                            licenseKey: "${licenseKey}",
                            applicationID: "${applicationID}",
                        };

                        NREUM.info = {
                            beacon: "bam.nr-data.net",
                            errorBeacon: "bam.nr-data.net",
                            licenseKey: "${licenseKey}",
                            applicationID: "${applicationID}",
                            sa: 1,
                        };
                    `,
                    }}
                    id="new-relic-browser-agent"
                    type="text/javascript"
                />
                <Script src="/new-relic.js" />
            </head>
            <body className={inter.className}>
                <div className="p-4">{children}</div>
            </body>
        </html>
    );
}
