import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const licenseKey = process.env.NEXT_PUBLIC_NEW_RELIC_LICENSE_KEY;
const applicationID = process.env.NEXT_PUBLIC_NEW_RELIC_APPLICATION_ID;

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <head>
                {/* eslint-disable-next-line @next/next/no-sync-scripts */}
                <script src="/new-relic.js" type="text/javascript" />
            </head>
            <body className={inter.className}>
                <div className="p-4">{children}</div>
            </body>
        </html>
    );
}
